name: Build

on:
  push:
    branches:
      - develop
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Installation des dépendances
        run: npm ci

      - name: Exécution des tests unitaires avec couverture
        run: npm run test:unit -- --coverage --run

      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@v3.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-and-push-docker:
    name: Build & Push Docker Image
    needs: sonarqube # N'exécute ce job que si SonarQube est OK !
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Donne le droit à GitHub d'écrire l'image dans ton profil

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Connexion au GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Jeton automatique fourni par GitHub

      - name: Configuration de Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build de l'image et Push sur GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/mon-portfolio:latest
            ghcr.io/${{ github.actor }}/mon-portfolio:${{ github.sha }}