name: Build

on:
  push:
    branches:
      - develop
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Désactive les clones superficiels pour une meilleure pertinence de l'analyse

      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Installation des dépendances
        run: npm ci

      - name: Exécution des tests unitaires
        run: npm run test:unit -- --run

      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@v3.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}